spring.application.name=gameclub
server.port=4269

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.datasource.url=jdbc:sqlite:./data/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.debug=true
logging.level.org.springframework.context=DEBUG
logging.level.org.springframework.security=DEBUG

#Base64-encoded 256-bit key; replace in production
jwt.secret=bWFrZS10aGlzLWEtMzItYnl0ZS1zZWNyZXQta2V5ISE=
# 24 hours in milliseconds
jwt.expiration=86400000
# In hours
invitation.expiration=48
# Maximum valid invitations per user
invitation.maxInvitations=4
invitation.defaultUses=1